using System.Collections.Generic;
using UnityEngine;

public class Story : MonoBehaviour
{
  public static Dictionary<(int, int), string> Parts { get; } = new Dictionary<(int, int), string>()
  {
    { (1, 1), "Humaaanity had gotten tired of the dirty rocks on earth, and went into the sky to see if there were any fresh ones up there." },
    { (1, 2), "It turned out there was nothing BUT rocks in outer space. Rocks and gas and nothing. Rocks no one was fighting over. Yet." },
    { (1, 3), "First they built ships on earth. Then they built them in space. Then they build ship-building ships and from there it got ridiculous. Everyone wanted those rocks." },
    { (1, 4), "Over decades and centuries, tiny ships swarmed Mars, Jupiter and Saturn's more popular moons, Mercury. Most people left Venus alone because it'll kill you, but some even went there. Ships took all the good spots and started wasting each other with bombs and ramming into each other." },
    { (1, 5), "Factions began to form to get dibs on the best space rocks. Soon the real power was in space, and those on earth could only watch as the carnage unfolded. It was free streaming 24/7 epic space battles. Except for all the people dying, it was pretty cool. A lot of it was just robot ships, but some of the robot ships could feel human emotions and that was maybe even worse." },
    { (1, 6), "While trying to find the best possible rocks, scientists found that among the stars, there was no other life, no other civilizations. There was just our earth. Just humans. Unless some of the rocks could talk. You can talk to a rock, but no one has heard one talk back. There are probably not talking rocks." },
    { (1, 7), "" },
    { (1, 8), "" },
    { (1, 9), "" },
    { (1, 10), "The fact that we were alone in the universe made everyone very sad. Even the robots got sad, the ones that could. Everyone was so sad that they stopped caring about rocks for awhile. For the first time in earth's history, no one was fighting except on the internet. Thus began the great era of peace." },
    { (2, 1), "As it always does, peace came too late. The earth was boiling over. All the good rocks had been used up making space ships to destroy other space ships. Yes all of them. Somehow. And there wasn't enough left to spread to other stars. Peak space-gas had long past." },
    { (2, 2), "All of humanity switched over to working on the problem of their species' future---the ones who weren't too busy, and barely anyone was. But the other stars just seemed too far away." },
    { (2, 3), "Studying rocks from the far reaches of space, a brilliant team of scientists discovered a new element, picolinium. It was green and it glowed, and it smelled like hope. And it also smelled like pickles." },
    { (2, 4), "All the atoms in picolinium were backwards and it could bend space. Peole tried to use it to make time machines and stop the wars before everyone used up all the good rocks, but obviously it didn't work. People really liked to fight back then." },
    { (2, 5), "Centuries passed, and when all hope seemed lost, they figured out how to use picolinium to make a ship go really fast. With the Prometheus Drive, a ship could jump to another star much faster than a regular gas powered one. The only problem was there was only enough left for a single ship. They called it the Stellar Flame." },
    { (2, 6), "" },
    { (2, 7), "" },
    { (2, 8), "" },
    { (2, 9), "" },
    { (2, 10), "" },
    { (3, 1), "The Stellar Flame hopped from star to star looking for more picolinium. Generations lived and died aboard the tiny vessel. From earth everyone cheered it on (with a very long delay due to how physics works)." },
    { (3, 2), "The ship traveled so far into space that people lived entire lives before a single message reached the vessel and came back. Small picolinium deposits were found, but only enough to continue the journey. Don't tell anyone back on earth you used it to put a jump module on your drone. They won't understand." },
    { (3, 3), "The people back on earth made advances to the picolinium drive, but there was no way to implement them so far from the ship without the giant ship-building ship builder factory factories and other such nonsense." },
    { (3, 4), "The Stellar Flame pointed its scanners to the far reaches of space. Larger picolinium signatures were detected, but even traveling faster than a light beam it would take a long time to reach them. Those aboard wondered how light could keep going without getting tired. Physicists still don't know." },
    { (3, 5), "Earth tried and failed to send astronauts with sublight engines running on rock fumes to other stars. That cryostasis stuff just isn't feasible. A human popsicle can't come back to life no matter how much you lick it. There was no choice but to keep going and to hope one day they would stumble on a big enough deposit to make it back with picolinium to spare." },
    { (3, 6), "" },
    { (3, 7), "" },
    { (3, 8), "" },
    { (3, 9), "" },
    { (3, 10), "" },
    { (4, 1), "Eons passed. Faster than light travel messed with everyone's heads, and few were sure how much time had passed exactly. Messages from earth kept coming, but there was little point in sending much back. It was really boring to chat with someone on a five hundred year delay." },
    { (4, 2), "Large picolinium deposits were found in the deepest reaches of space. Past where the big bang happened (probably...). The crew of Stellar Flame seeded worlds as they went, and its decendent ships all bore earth's fire. But the math still didn't work out no matter how many times they re-did it. There wasn't enough to return to earth." },
    { (4, 3), "Ships with the picolinium drive bearing earth's flame went off in every direction, hoping to find the mother lode and rekindle earth's hope. Most of them went without hats or powerups, because there were more important things than looking cool." },
    { (4, 4), "The same old transmissions from earth echoed in the stellar void, seeming to repeat from centuries earlier. No one was sure of the fate of their original planet. It was much too soon for it to have gotten swallowed by the sun, but they definitely could have blown it up or something. They still loved blowing things up." },
    { (4, 5), "Humanity continued to advance in the far reaches of space. A much-faster-than-light communication network was established between the interstellar fleet. You could play games on it and everything. But more importantly, it let them cross check messages from earth. A message no one else had heard before was detected and broadcast to the network." },
    { (4, 6), "" },
    { (4, 7), "" },
    { (4, 8), "" },
    { (4, 9), "" },
    { (4, 10), "" },
    { (5, 1), "Far, far away from the fleet, farther than you can imagine, earth still held life. There were even some people on Venus that she hadn't managed to kill. But the solar system's colonies had failed. It's people were dying out." },
    { (5, 2), "The message they received was not asking for help. Humanity had reached far beyond its tiny solar system and reached unfathomable depths in the endless sea of space. A few people had even claimed to have heard a rock talking." },
    { (5, 3), "The network vowed to one day return to earth, but so long had passed that earth seemed less important than it once had." },
    { (5, 4), "When the lone ship returned, bearing the same name as the original Stellar Flame, the sun had grown to twice its size. They were too late to pick anyone up if they still needed a ride somewhere. They were awfully sorry about that." },
    { (5, 5), "Earth was covered in the charred remains of forests, plains, and mountains, not an inch of it sullied with silly rocks pounded into shapes of cubes with glass covered holes." },
    { (5, 6), "They flagged down a passing ship. It was full of those robots that could be sad. Some of them looked like humans' original shape. They pointed to the moon, saying the humans had built something there half a billion years ago. While they were still around." },
    { (5, 7), "On earth's moon stood a monument. A replica of the the first Stellar Flame, humanity's hope, blasting from a globe into a field of stars. Inscribed on a pitted plinth was earth's last wish. *May the fire that started here never go out.* It was made of some sweet rocks and everyone agreed it was really cool." },
    { (5, 8), "" },
    { (5, 9), "" },
    { (5, 10), "" },
  };
}
